import 'package:flutter/material.dart';
import 'package:flutter_chat_ui/flutter_chat_ui.dart';
import 'package:flutter_chat_types/flutter_chat_types.dart' as types;
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:firebase_database/firebase_database.dart';


class StoryChatPage extends StatefulWidget {
  final String loggedInUserId;
  final String secondUserId;

  StoryChatPage({required this.loggedInUserId, required this.secondUserId});

  @override
  _StoryChatPageState createState() => _StoryChatPageState();
}

class _StoryChatPageState extends State<StoryChatPage> {
  final List<types.Message> messages = [];
  final TextEditingController _textController = TextEditingController();
  final String apiKey =
      "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"; // Replace with your actual API key
  final String chatId = "fixed-chat-id";

  @override
  void initState() {
    super.initState();
    _listenForMessages();
  }

  void _listenForMessages() {
    DatabaseReference messagesRef = FirebaseDatabase.instance.ref('messages');
    messagesRef.onChildAdded.listen((event) {
      final data = Map<String, dynamic>.from(event.snapshot.value as Map);
      final newMessage = types.TextMessage(
        author: types.User(id: data['senderId']),
        createdAt: data['timestamp'],
        id: event.snapshot.key ?? 'unknown-id',
        text: data['text'],
      );
      setState(() {
        messages.insert(0, newMessage);
      });
    });
  }

  void _handleSendPressed(types.PartialText text) async {
    final userText = text.text.trim();
    if (userText.isEmpty) return;

    _sendMessage(userText, widget.loggedInUserId, chatId); // Send user message
    await _getResponse(userText);
  }

  void _sendMessage(String text, String senderId, String chatId) async {
    DatabaseReference ref = FirebaseDatabase.instance.ref('messages');
    String messageId = ref.push().key ?? 'default-id'; // Generating a unique ID for the message

    await ref.child(messageId).set({
      'chatId': chatId, // Ensure this is correctly set
      'messageId': messageId, // messageId generated by Firebase
      'senderId': senderId,
      'text': text,
      'timestamp': ServerValue.timestamp, // Uses Firebase server's timestamp
    }).catchError((error) {
      // Handle any errors here
      print('Error sending message: $error');
    });
  }

  Future<void> _getResponse(String userText) async {
    final response = await http.post(
      Uri.parse('https://api.openai.com/v1/engines/davinci/completions'),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $apiKey',
      },
      body: jsonEncode({'prompt': userText, 'max_tokens': 150}),
    );

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      final aiText = 'This is the chatGPT response: ' + data['choices'][0]['text'].trim();
      _sendMessage(aiText, 'ai-id', chatId); // Send AI response
    } else {
      // Handle error...
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: _buildAppBar(),
      body: _buildChatBody(),
    );
  }

  AppBar _buildAppBar() {
    return AppBar(
      leading: _buildBackButton(),
      title: const Text('Pirate Story'),
      actions: [_buildProfileButton()],
    );
  }

  IconButton _buildBackButton() {
    return IconButton(
      icon: const Icon(Icons.arrow_back_ios_new_outlined),
      onPressed: () {
        Navigator.maybePop(context);
      },
    );
  }

  IconButton _buildProfileButton() {
    return IconButton(
      padding: const EdgeInsets.only(right: 15),
      icon: const Icon(Icons.account_circle, size: 35),
      onPressed: () {
        // Navigate to profile page...
      },
    );
  }

  Column _buildChatBody() {
    return Column(
      children: [
        Expanded(
          child: Chat(
            messages: messages,
            user: types.User(id: widget.loggedInUserId),
            theme: _buildChatTheme(),
            showUserNames: true,
            customBottomWidget: _buildInputField(),
            onSendPressed: _handleSendPressed,
            customMessageBuilder: (message, {required int messageWidth}) {
              if (message is types.TextMessage) {
                return _buildCustomTextMessage(message as types.TextMessage, messageWidth);
              }
              return _buildDefaultMessageContainer(message, messageWidth);
            },
          ),
        ),
      ],
    );
  }

  DefaultChatTheme _buildChatTheme() {
    return DefaultChatTheme(
      primaryColor: const Color(0xFF0A2342),
      secondaryColor: Colors.teal,
      dateDividerTextStyle: TextStyle(color: Colors.grey[600], fontSize: 12),
      inputTextDecoration: InputDecoration(
        contentPadding: const EdgeInsets.symmetric(vertical: 30, horizontal: 0),
        hintText: "Type a message",
        border: InputBorder.none,
        hintStyle: TextStyle(color: Colors.grey[500]),
      ),
    );
  }

  Widget _buildInputField() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 12),
      color: Theme.of(context).scaffoldBackgroundColor,
      child: Row(
        children: [
          Expanded(
            child: TextField(
              controller: _textController,
              decoration: InputDecoration(
                hintText: "Type a message",
                border: InputBorder.none,
                hintStyle: TextStyle(color: Colors.grey[500]),
              ),
            ),
          ),
          IconButton(
            icon: const Icon(Icons.send, color: Color(0xFF0A2342)),
            onPressed: () => _handleSendPressed(types.PartialText(text: _textController.value.text)),

          ),
        ],
      ),
    );
  }

  Widget _buildCustomTextMessage(types.TextMessage message, int messageWidth) {
    // Customize the appearance of text messages here
    return Container(
      alignment: message.author.id == widget.loggedInUserId
          ? Alignment.centerRight
          : Alignment.centerLeft,
      child: Container(
        padding: EdgeInsets.all(8.0),
        margin: EdgeInsets.all(4.0),
        decoration: BoxDecoration(
          color: message.author.id == widget.loggedInUserId
              ? Colors.blue
              : Colors.grey,
          borderRadius: BorderRadius.circular(8.0),
        ),
        child: Text(
          message.text,
          style: TextStyle(color: Colors.white),
        ),
      ),
    );
  }


  Widget _buildDefaultMessageContainer(
      types.CustomMessage message, int messageWidth) {
    // Customize the appearance of other types of messages here
    return Container(
      padding: EdgeInsets.all(8.0),
      margin: EdgeInsets.all(4.0),
      decoration: BoxDecoration(
        color: Colors.red,
        borderRadius: BorderRadius.circular(8.0),
      ),
      child: Text(
        'Unsupported message type',
        style: TextStyle(color: Colors.white),
      ),
    );
  }

}